### ISSUE TITLE
支持使用Llama-factory进行推理吗

### ISSUE THREAD

**Issue by ToviHe** [THUDM/CodeGeeX4#13]
如题

**Comment by xinpeng-zhang** [comment]
暂时没有做Llama-factory的适配呢，您可以尝试使用vllm或者ollama进行推理

**Comment by ToviHe** [comment]
> 暂时没有做Llama-factory的适配呢，您可以尝试使用vllm或者ollama进行推理

https://github.com/hiyouga/LLaMA-Factory/issues/4730
已经支持了，只是transformers版本需要改下

**Comment by xinpeng-zhang** [comment]
感谢分享
