### ISSUE TITLE
关于嵌入模型的选择问题

### ISSUE THREAD

**Issue by ImJoyed** [THUDM/CodeGeeX4#22]
目前demo中的嵌入模型使用的是在线服务，embedding-2模型。但是因为我们公司的开发环境是不联网的，所以想请教一下embedding-2模型是否有开源计划。
或者使用其它的开源嵌入模型会不会影响效果。因为目前我在网上找到的资料，关于RAG基本上都是针对自然语言文本的，不清楚代码和自然语言在向量转换和向量检索方面是否一样。

**Comment by ShaoboZhang** [comment]
> 目前demo中的嵌入模型使用的是在线服务，embedding-2模型。但是因为我们公司的开发环境是不联网的，所以想请教一下embedding-2模型是否有开源计划。 或者使用其它的开源嵌入模型会不会影响效果。因为目前我在网上找到的资料，关于RAG基本上都是针对自然语言文本的，不清楚代码和自然语言在向量转换和向量检索方面是否一样。

你好，这个我们目前没有开源计划。你可以考虑用其他开源模型替代，把相关代码做个替换就好。

**Comment by ImJoyed** [comment]
ok，感谢回答。
