### ISSUE TITLE
IDEA插件不支持本地模式

### ISSUE THREAD

**Issue by ConleyKong** [THUDM/CodeGeeX4#27]
看演示编辑器插件中可以使用本地模式连接模型工具，但是在idea中安装最新版的插件后没有发现有可以开启本地模式的页面

**Comment by crazygo** [comment]
请从右上角 ... 中选择「本地模式」

![CleanShot 2024-07-13 at 23 21 48@2x](https://github.com/user-attachments/assets/22a9bba4-2652-4198-b3e0-85eceee37372)

**Comment by ConleyKong** [comment]
> 请从右上角 ... 中选择「本地模式」
> 
> ![CleanShot 2024-07-13 at 23 21 48@2x](https://private-user-images.githubusercontent.com/9395888/348480565-22a9bba4-2652-4198-b3e0-85eceee37372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMDUwMjksIm5iZiI6MTcyMTAwNDcyOSwicGF0aCI6Ii85Mzk1ODg4LzM0ODQ4MDU2NS0yMmE5YmJhNC0yNjUyLTQxOTgtYjNlMC04NWVjZWVlMzczNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTVUMDA1MjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGJiZDBiNTkyOTNkOTI3YThhMjcwMjljYTNhYzQ4M2JlNjdlY2M4Nzk4Yjg1Mzg2YTEwZmU3YmE5ZTQ1NTRjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FBMkBxuYJxAOgO5w4qVPUcdzHwMtvDrV8sLH-H61oY0)

谢谢，找到了
