### ISSUE TITLE
ollama 403 err

### ISSUE THREAD

**Issue by TianZhenGG** [THUDM/CodeGeeX4#30]
run on ollama, 403 err

**Comment by Stanislas0** [comment]
> run on ollama, 403 err

Please run the following command first to solve the cross-domain HTTP request issue:
```
export OLLAMA_ORIGINS="*"
```

**Comment by liseri** [comment]
@Stanislas0 建议 跨域设为默认的吧

**Comment by liseri** [comment]
@Stanislas0 建议 跨域设为默认的吧，或者放到配置里；
