### ISSUE TITLE
idea的插件配置本地模式后无法正确向openai接口发送数据，一直报错

### ISSUE THREAD

**Issue by ConleyKong** [THUDM/CodeGeeX4#31]
按照官网提示进行了本地配置，配置页面显示连接正确：
![image](https://github.com/user-attachments/assets/b129abf0-60ab-4609-a225-bcf2c4e01b17)

但是发送消息时提示后台错误：

![e222575d9a77a6de3744c46a50a6481](https://github.com/user-attachments/assets/afcc10d6-2de1-449a-affe-54ea8c620dcc)

但是相同的模型服务器配置同事使用vscode可以正常访问本地模型，所以我怀疑咱这个idea的插件我是不是配置的不对还是使用姿势不对？

**Comment by xinpeng-zhang** [comment]
![image](https://github.com/user-attachments/assets/f059f6a1-06c6-4e0f-833f-6fd202574d89)
您可以扫码进群，我们有专业的技术同学帮您解决问题

**Comment by ConleyKong** [comment]
谢谢，我进去问问

**Comment by humphreyde** [comment]
> ![image](https://private-user-images.githubusercontent.com/53964972/348966831-f059f6a1-06c6-4e0f-833f-6fd202574d89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Mjg2MjcsIm5iZiI6MTcyMjkyODMyNywicGF0aCI6Ii81Mzk2NDk3Mi8zNDg5NjY4MzEtZjA1OWY2YTEtMDZjNi00ZTBmLTgzM2YtNmZkMjAyNTc0ZDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA3MTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZDU1Yzg0YjQ3YjU0NzEwMDFiMGVlMWQzYzQ4NjI4YjFhM2E5OGE2MDgwYjM3YmE1ZGY1NDYzOGQ3ZWY0MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xc4-Jz8QyeOp6EaiWsdK13LfuJGoFTvoFZQ1b38u-wU) 您可以扫码进群，我们有专业的技术同学帮您解决问题

你好，
1.我想请问openai api客户端访问后返回的response格式是什么，貌似和openai的不匹配
2.能否让我进群，二维码过期了。
