### ISSUE TITLE
set plugin to use local api

### ISSUE THREAD

**Issue by clude** [THUDM/CodeGeeX4#4]
do you have a plan to make the vs/jetbrains plugin supporting local deployed CodeGeeX Service

**Comment by ImJoyed** [comment]
The latest plugins are now supported.

**Comment by clude** [comment]
cooooooool!!!!  
found the latest VS plugin working on local ai model now!
will the next released jetbrains plugin have the same feature ?

**Comment by ShaoboZhang** [comment]
> cooooooool!!!! found the latest VS plugin working on local ai model now! will the next released jetbrains plugin have the same feature ?

Yes, but Jetbrains has a stricter review process, so it takes a bit longer than vs code.

**Comment by agdkgg** [comment]
ollama 本地 连接失败  403错误代码，网络 后缀名试了几个，是代码还没修改吗？

**Comment by limingchina** [comment]
I've seen those settings:
```
 "Codegeex.Local": {
        
        "apiURL": "",
        "useChatGLM": true,
        "chatGLM": {
            "apiKey": "",
            "model": ""
        },
```
What should be set for them? @clude , have you tried it successfully?

**Comment by clude** [comment]
<img width="624" alt="image" src="https://github.com/THUDM/CodeGeeX4/assets/3115168/3d9af6bf-68b5-47e4-9ef9-5342fe2651e2">
you just need to config the openai api address and model name。 
by the way , if u use ollama as a service , do not forget set the env value:  OLLAMA_ORIGINS="*"

**Comment by Choumingzhao** [comment]
Got same error with codegeex vscode plugin.   
Using Ollama api: http://localhost:11434/api/generate.  Ollama API test passed with curl both on local and remote.  
Output from CodeGeeX Local in VSCode:
```quote
[info] [Model Config] try to connect: http://localhost:11434/api/generate

data: {
  "messages": [
    {
      "role": "user",
      "content": "Hi"
    }
  ],
  "model": "codegeex4",
  "stream": false,
  "temperature": 0.9,
  "top_p": 0.9,
  "stop": []
}
headers: {}
[error] [Model Config] error: {
  "message": "Network Error",
  "name": "AxiosError",
  "stack": "AxiosError: Network Error\n    at u.onerror (https://vscode-remote+ssh-002dremote-002bjss.vscode-resource.vscode-cdn.net/home/user/.vscode-server/extensions/aminer.codegeex-2.12.2/webview-ui/dist/assets/index.js:55:1051909)\n    at XMLHttpRequest.r (https://vscode-remote+ssh-002dremote-002bjss.vscode-resource.vscode-cdn.net/home/user/.vscode-server/extensions/aminer.codegeex-2.12.2/webview-ui/dist/assets/index.js:35:854177)",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "adapter": ["xhr", "http"],
    "transformRequest": [null],
    "transformResponse": [null],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json",
      "Exp-Id": "",
      "Variant-Id": "",
      "Is-Exp-Active": "false"
    },
    "baseURL": "https://codegeex.cn/prod",
    "method": "post",
    "url": "http://localhost:11434/api/generate",
    "data": "{\"messages\":[{\"role\":\"user\",\"content\":\"Hi\"}],\"model\":\"codegeex4\",\"stream\":false,\"temperature\":0.9,\"top_p\":0.9,\"stop\":[]}"
  },
  "code": "ERR_NETWORK",
  "status": null
}
```

**Comment by clude** [comment]
For me , I tried CodeQwen1.5 on ollama 0.1.44 and CodeGeex4-9b on Ollama 0.2.5, both are working。

currently, if VsCode is your primary IDE , "Continue" may be the best choice, it is stable、customizable and has much more features than CodeGeex plugin in local mode.
but "Continue"'s  jetbrains plugin will disappoint you， it is not stable, always crash。 

so, I still have high hopes on the CodeGeex plugin's local model, hope it has the full feature as the online mode version.
