### ISSUE TITLE
ollama运行codegeex4一段时间后输出GGGGGGGGG

### ISSUE THREAD

**Issue by wxfvf** [THUDM/CodeGeeX4#40]
我用ollama运行codegeex4运行一段时间后，会输出GGGGGGGGG，但刚加载后是正常的，GPU为双4090，ollama版本0.2.5。这个问题可以复现，重新加载后恢复正常，一端时间后又这样了。
我看ollama项目有个类似的issue，GLM4好像也有类似的问题。

**Comment by zhaoM0** [comment]
我这儿一开始就是GGGGG

**Comment by Smalldy** [comment]
截个图看看？

**Comment by yangtang-cn** [comment]
每周总会GGGG好多次，然后重启会回复正常，OLLAMA中使用codegeex4
