### ISSUE TITLE
IDEA升级到2024.2后codegeex插件报错

### ISSUE THREAD

**Issue by dododcdc** [THUDM/CodeGeeX4#55]
报错信息：Plugin 'CodeGeeX' (version '2.13.0-223') is not compatible with the current version of the IDE, because it requires build 241.* or older but the current build is IU-242.20224.300

**Comment by crazygo** [comment]
感谢你的反馈，我们已经注意到这个影响并在做兼容的工作，预计不久就会上线。

**Comment by lianshuze** [comment]
刚更新2024.2，期待尽快适配

**Comment by qwecxzpoi** [comment]
已经可以关闭这个 issue 了，刚刚更新了
