### ISSUE TITLE
is function calling supported?

### ISSUE THREAD

**Issue by foldl** [THUDM/CodeGeeX4#8]
I have tested this model with same system prompt of GLM4. This model only emits parameters, but not the function name. For example, here, `get_weather` is not generated:

```
You  > what's the weather like in beijng?
A.I. > 
{"city_name": "beijing"}
```

**Comment by ShaoboZhang** [comment]
> I have tested this model with same system prompt of GLM4. This model only emits parameters, but not the function name. For example, here, `get_weather` is not generated:
> 
> ```
> You  > what's the weather like in beijng?
> A.I. > 
> {"city_name": "beijing"}
> ```

Hi, we uploaded a function calling demo, you may check it. 
[demo](https://github.com/THUDM/CodeGeeX4/blob/main/function_call_demo/main.py)

**Comment by foldl** [comment]
Got it. I forgot to have a check on `tokenization_chatglm.py`.

I managed to do a full demo here:

https://github.com/foldl/chatllm.cpp/blob/master/docs/tool_calling.md#codegeex4
